### ISSUE TITLE
util folder should placed under src directory

### ISSUE THREAD

**Issue by Huang-Chuan** [JulianoLagana/MT3#1]
`Traceback (most recent call last):
  File "src/training.py", line 17, in <module>
    from data_generation.data_generator import DataGenerator
  File "/home/dongxiwei519/MT3/src/data_generation/data_generator.py", line 9, in <module>
    from util.misc import NestedTensor
ModuleNotFoundError: No module named 'util'`

**Comment by JulianoLagana** [comment]
Thanks! Solved with commit 35c5d789382f164bd3cb5703d9f7dc59d20d4573.
